### ISSUE TITLE
server silent crash

### ISSUE THREAD

**Issue by Swrup** [robur-coop/httpcats#3]
Hello,

I encountered this problem when making a website with modestly sized cat pictures.

The server crashed after some requests.
It seems to happen with big response and often after some Unexpected exception: \"Unix.Unix_error(Unix.ECONNRESET, write, ..." or "Unix.ENOTCONN, shutdown, ... ".

I reproduced it on this branch in the example: https://github.com/Swrup/httpcats/tree/silent-crash-debug
When I run this modified example and connect to it with firefox, the server crashes after a few F5

**Comment by dinosaure** [comment]
It should be fixed by https://git.robur.coop/robur/httpcats/pulls/4, can you retest?

**Comment by Swrup** [comment]
nice
its seems to work well now

thanks
